TeamDATEROAD/DATEROAD-iOS

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/DATEROAD-iOS.entitlements
- setting/#3
provisioning profile 세팅
.p12 파일 형식으로 인증서입니다
파일 다운받고 더블클릭하고 보내드린 비밀번호 입력하면 자동으로 인증서 등록돼요!
개발, 배포 하는데 사용되는 파일입니다
프로젝트 / 타겟 -> Signing & Capabilities 들어가서 debug랑 release에 모두 파일 넣어주셔야 합니다
Automatically manage signing 해제 해주시고 세팅해주세요
없어욤
- Resolved: #3
=> [SETTING] provisioning profile 세팅 (#3)

DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/DR_Black.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/DR_White.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray100.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray200.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray300.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray400.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray500.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/GrayScale/Gray600.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/AlertRed.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/DeepPurple.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/LightLime.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/LightPurple.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Lilac.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Lime.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/MediumPurple.colorset/Contents.json, DATEROAD-iOS/DATEROAD-iOS/Global/Resources/Assets.xcassets/Colors/Main/Pink.colorset/Contents.json
- #10 
- 컬러 세팅했습니다.
```swift
view.backgroundColor = UIColor(named = "AlertRed")
view.backgroundColor = UIColor(resource: .색상이름)
view.backgroundColor = .alertRed
``` 
- 셋 중 하나로 사용하시면 됩니다.
```swift
view.backgroundColor = .drWhite
view.backgroundColor = .drBlack
``` 
- 커스텀 블랙 / 화이트 컬러 이름은 각각 "DRBlack", "DRWhite"입니다.
- 나머지는 앞에 DR 없어요 ~! 그냥 색깔 이름입니다.
- Resolved: #10
=> [CHORE] 컬러 세팅

DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/ViewModels/ProfileViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
=> [FIX] 회원탈퇴 로직 수정 (#92)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Info.plist, DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRWebViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Network/DateSchedule/DateScheduleTargetType.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift
- feature/#96 
카카오톡 공유하기 연결
- Resolved: #96
=> [FEAT] 카카오톡 공유하기 연결 (#96)

DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/DRWebViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
- #93
카카오톡 앱이 없을 경우 웹으로 카카오톡 공유하는 기능을 구현했습니다.
카카오 계정 정보가 없을 경우 카카오톡 로그인 페이지로 이동합니다.
- Resolved: #93
=> [FEAT] 카카오톡 공유하기 (웹) 구현 (#93)

DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetFilteredDateCourseResponse.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/NewDateCourseCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
=> [FIX] 1차 자체 QA 적용 (#99)

DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift, DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseService.swift, DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/AddCourseTargetType.swift, DATEROAD-iOS/DATEROAD-iOS/Network/AddCourse/DTO/PostAddCourseRequest.swift, DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/AddScheduleService.swift, DATEROAD-iOS/DATEROAD-iOS/Network/AddSchedule/DTO/PostAddScheduleRequest.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Cells/AddSecondViewTableViewCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddSecondView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/InAddScheduleFirstView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/InAddScheduleSecondView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseNavBarViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/Cells/TagCollectionViewCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/Cells/TendencyTagCollectionViewCell.swift
=> [FEAT] '일정 등록 불러오기' & '지난 데이트 코스 등록하기' 구현 (#97)

DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift, DATEROAD-iOS/DATEROAD-iOS/Network/Course/CourseService.swift, DATEROAD-iOS/DATEROAD-iOS/Network/Course/CourseTargetType.swift, DATEROAD-iOS/DATEROAD-iOS/Network/CourseDetail/LikeCourseService.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/LocationFilterViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/TagInfoCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseBottomTabBarView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/InfoBarView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift
=> [FIX] 좋아요 API 연결 & 필터링 수정 (#107)

DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Models/MainModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
- #111 
- 메인뷰 컴포넌트들 모두 화면 연결했습니다
- 광고배너 일단 코스상세로 연결해두었습니다.
- Resolved: #111
=> [FEAT] 메인뷰 화면 연결

DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
=> [FIX] 미보완 사항 수정 (#110)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
=> [Fix] 마이페이지 총 포인트 실시간 업데이트 안되는 오류 수정 (#126)

DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift
- #129
시간 버튼 고정값 해제하여 CourseViewCell 시간값 고정 오류 해결
- Resolved: #129
=> [FIX] CourseViewCell 시간값 고정 오류 해결 (#129)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/xcshareddata/xcschemes/DATEROAD-iOS.xcscheme, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift
=> [Fix] ImageCarouselCell QA 반영 (#131)

DATEROAD-iOS/DATEROAD-iOS/Presentation/Base/BaseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/ViewModels/PointSystemViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointSystem/Views/PointSystemViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashView.swift
=> [FIX] 자체 QA (#135)

DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/BannerImageCollectionViewCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
- refactor/#127 
- Resolved: #127
=> [REFACTOR] 리팩토링 (#127)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Application/SceneDelegate.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/EditProfile/Views/EditProfileViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Onboarding/Views/OnboardingViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
- feature/#145
- 자동 로그인 구현
- 탈퇴 로직 수정
없습니당
|기능|스크린샷|
|:--:|:--:|
|아이폰15Pro|![Simulator Screen Recording - iPhone 15 Pro - 2024-08-09 at 17 18 48](https://github.com/user-attachments/assets/315414cb-d938-46a3-9b47-ee09371ec1e1)|
- Resolved: #145
=> [FEAT] 자동 로그인 구현 (#145)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/UIImageView+.swift, DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/Cells/CourseListCollectionViewCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/ImageCarouselCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Models/CourseDetailModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/ContentMaskView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseBottomTabBarView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailBottomTabBarView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/DeleteCourseSettingView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift
- refactor/#151 
코스 상세 분기 처리 코드 최대한 간략하게 줄이려고 했습니다..ㅎㅎ
상단 네비게이션 바에서 더보기 클릭 시 나오는 바텀 시트 디자인 변경 사항 반영하고
신고하기 기능 추가되어서 세팅해두었습니다
kingfisher 라이브러리를 활용하여 이미지 로드와 캐싱하는 extension을 추가했습니당
```
extension UIImageView {
func kfSetImage(with urlString: String?, placeholder: UIImage? = nil) {
guard let urlString = urlString, let url = URL(string: urlString) else {
self.image = placeholder
return
}
self.kf.setImage(with: url, placeholder: placeholder)
}
}
```
지금 코스 타임라인 보면 글마다 인덱스가 1인것도 있고 2인 것도 있는데 
더미 넣을때 잘못넣은거라 서버에서 0부터 시작하는게 맞다고 합니다! 
그래서 이상한게 아니라는 점 참고해주세욤..ㅎㅎ
|기능|스크린샷|
|:--:|:--:|
|아이폰15Pro|![Simulator Screen Recording - iPhone 13 mini - 2024-08-15 at 02 38 28](https://github.com/user-attachments/assets/f84e319e-8df6-4527-ba51-866bd1055603)|
- Resolved: #151
=> [REFACTOR] 코스 상세 버그 수정 및 리팩토링 (#151)

DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift, DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift, DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/Serviceable.swift, DATEROAD-iOS/DATEROAD-iOS/Network/Main/DTO/GetMainUserProfileResponse.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseSecond/AddCourseSecondViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseThird/AddCourseThirdViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleSecond/AddScheduleSecondViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Login/Views/LoginViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/UpcomingDateCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/MyRegisterCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/Views/SplashViewController.swift
- fix/#152
- 데이트 일정 타이틀 텍스트 제한 설정
- 스크롤에 따른 배경색 설정
- 재발급 로직 수정
- 메인 뷰 배너 인덱스 바인딩 수정
현재 재발급 로직은
1. 토큰 재발급이 필요한 경우, 각 서버 통신의 결과로 토큰 재발급 에러 코드를 받게 되고 토큰 재발급 서버 통신을 해줍니다
2. 이때 토큰 재발급에 실패한 경우 다시 스플래시로 돌아가도록 설정해두었습니다.
3. 토큰 재발급에 성공한 경우 각자 진행하고 있었던 서버 통신을 다시 해주시면 됩니다! (이 로직은 각자 추가해주세요!)
없습니다
- Resolved: #152
=> [FIX] 메인 뷰 자체 QA 적용 (#152)

DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/ViewModels/AddCourseViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/ViewModels/AddScheduleViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/AddSchedule/Views/AddScheduleFirst/AddScheduleFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Models/LocationModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Commons/LocationFilter/Views/LocationFilterViewController.swift
- `fix/#156`
- `코스 등록하기` 파트 코드 수정
- `일정 등록하기` 파트 코드 수정
- 지역 필터링 디자인 변경 적용
- 지역 필터 중 소분류 추가는 적용되지 않았습니다.
- `코스 or 일정 등록` 상황에서 서울, 경기 각 전체 탭 삭제만 적용되었어요!
- 처음 브랜치 생성시 `fix`가 아닌 `fit`으로 생성한 것을 모든 커밋 이후에 알게되었습니다..!
- 이런 때에는 해당 브랜치에서 아래 코드를 대괄호 빼고 입력해주시면 됩니다! 
`git branch -m [바꿀 브랜치 이름]`
|기능|스크린샷|기능|스크린샷|
|:--:|:--:|:--:|:--:|
|아이폰 12|<img src = "https://github.com/user-attachments/assets/dcd3b9a8-76de-4171-b6d2-0db8ab316fe7" width ="250">|아이폰 12 <br> 디자인 변경 적용|<img src = "https://github.com/user-attachments/assets/12bec252-6d9d-44a0-9735-314c10f54228" width ="250">|
- Resolved: #156
=> [FIX] '코스 등록', '일정 등록' 변경 사항에 따른 코드 수정 (#156)

DATEROAD-iOS/DATEROAD-iOS/Presentation/AddCourse/Views/AddCourseFirst/AddCourseFirstViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/DateTicketView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/EmptyTicketView.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Splash/ViewModels/SplashViewModel.swift
- feature/#173 
몇 개는 수민이거 이슈 해결하면서 다시 수정해놔서 컨플릭 생기면 해결해서 머지해놓을게욤
없습니다
- Resolved: #173
=> [FEAT] 스택 & 토큰 처리 (#173)

DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/ViewModels/PointViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/PointDetail/Views/PointDetailViewController.swift
- #183 
포인트내역 리팩 및 로딩뷰 + 에러뷰 적용했습니당
포인트내역 문구 잘못되었는데, 서버에서 내려주는 거라 수정 요청했습니다 ! 안드 확인 받고 다시 확인하겠습니당
중간에 깃 꼬여서 revert했는데 급해서.. 커밋 컨벤션 못 지켜서 죄송합니다 ㅠㅠ
https://github.com/user-attachments/assets/4016a66a-9a96-4e6a-93ac-79cec90545f0
- Resolved: #183
=> [REFACTOR] 포인트내역 리팩토링 (#183)

DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift, DATEROAD-iOS/DATEROAD-iOS/Global/Protocols/MainSectionLayout.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/HotDateCourseCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/Cells/MainHeaderView.swift
- fix/#195 
- 마이페이지 메인 → 포인트 시스템 소개 버튼이 ‘포인트 제도 소개’로 워딩 변경
- 홈화면 스크롤 여러번 또는 왔다갔다 할 때 버벅거리면서 배경 보라색으로 변경
- 메인 HOT & NEW 코스 카드 이미지 정사각형으로 변경
없어용
|워딩 변경|<img src = "https://github.com/user-attachments/assets/c6bbc0f4-f14e-4878-8e1d-20231562c2c5" width ="250">|배경색 수정|<img src = "https://github.com/user-attachments/assets/53750004-8419-4038-a9d8-3d1ff61d31bd" width ="250">|이미지<br>사이즈 변경|<img src = "https://github.com/user-attachments/assets/6740dacc-0c9b-43ae-89bf-2b7254fa680b" width ="250">|
- Resolved: #195
=> [FIX] 1차 iOS QA 적용 (#195)

DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift, DATEROAD-iOS/DATEROAD-iOS/Global/UIComponents/TabBarController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift
- feature/#214
1️⃣ User Property 
- 맨 처음 앱이 실행될 때 유저프로퍼티 세팅을 위해 뷰모델 초기화 시점에 서버 통신을 한 번 더 해주었습니다
- 초기화 시점에 서버 통신에 성공하면, 서버 통신 성공 관련 프로퍼티의 값이 true로 설정되기 때문에 viewWillAppear에서 로딩뷰 세팅 메소드를 호출해도 로딩뷰가 보이지 않게 됩니다. 따라서 viewDidLoad 시점에서 서버 통신 성공 관련 프로퍼티의 값을 false로 설정해주어 로딩뷰가 정상적으로 작동할 수 있도록 구현했습니다.
- 
``` Swift
// MyCourseListViewModel
init() {
setViewedCourseData()
setMyRegisterCourseData()
}
func setViewedCourseData() {
... 
NetworkService.shared.myCourseService.getViewedCourse() { response in
switch response {
case .success(let data):
let viewedCourseInfo = data.courses.map { MyCourseModel(courseId: $0.courseID,
thumbnail: $0.thumbnail,
title: $0.title,
city: $0.city,
cost: $0.cost.priceRangeTag(),
duration: ($0.duration).formatFloatTime(),
like: $0.like) } …
```
=> [FEAT] Amplitude 나머지 적용 (#214)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Application/AppDelegate.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Banner/Views/BannerDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/ViewModels/CourseViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Course/Views/CourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateScheduleViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateDetailViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/ViewModel/DateScheduleViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/ViewModels/MainViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Main/Views/MainViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/ViewModels/MyCourseListViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/ViewedCourseViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyPage/Views/MyPageViewController.swift
- fix/#220
없습니다
없습니다
- Resolved: #220
=> [FIX] 2차 QA 전 디테일 수정 (#220)

DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/ViewModels/CourseDetailViewModel.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/MyCourse/Views/NavViewedCourseViewController.swift
=> [FIX] 데이트 일정 불러오기 버그 수정 (#229)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Global/Extensions/Int+.swift, DATEROAD-iOS/DATEROAD-iOS/Global/Literals/StringLiterals.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Cells/CostInfoCell.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/CourseDetail/Views/CourseDetailViewController.swift
- fix/#232
코스 둘러보기 가격 바인딩 수정
0월 일 때, 무지출로 라이팅 수정
없어욤
|기능|스크린샷|
|:--:|:--:|
|아이폰 13 mini| ![Simulator Screen Recording - iPhone 13 mini - 2024-09-26 at 02 40 17](https://github.com/user-attachments/assets/ba273bed-4e5f-46bd-9bd1-be91675aacb6)|
- Resolved: #232
=> [FIX] 2차 QA 반영 #232

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Global/Settings/Configurations/Development.xcconfig
- feature/#236
- 버전 & 빌드 번호 업데이트
- url 변경
=> [Feat] 버전 & 빌드 번호 업데이트 (#236)

DATEROAD-iOS/DATEROAD-iOS.xcodeproj/project.pbxproj, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/PastDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/DateSchedule/View/UpcomingDateDetailViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/EditProfileViewController.swift, DATEROAD-iOS/DATEROAD-iOS/Presentation/Profile/Views/ProfileViewController.swift
- hotfix/#252
- Resolved: #252
=> [HOTFIX] 1.0.1 버전 수정 (#252)
